version: "3.7"

services:
  app:
    build: .
    stdin_open: true
    tty: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    environment:
      - BUNDLE_PATH=/gems

volumes:
  gem_cache:
